### ISSUE TITLE
[Question] What is a version of Nginx on the last release ?

### ISSUE THREAD

**Issue by iwebroot** [ononoki1/nginx#38]
Hello,
Before install the package, can you give the version of Nginx into Readme file ?
Thank you.

**Comment by ononoki1** [comment]
The release is always based on latest NGINX version. For example, now it's 1.25.1.

**Comment by iwebroot** [comment]
> The release is always based on latest NGINX version. For example, now it's 1.25.1.

Thank you.
I have the old version installed (1.23.4) and after installing this version for an upgrade, the Nginx version has not changed.
**OS** : Debian 11 Amd64
```
nginx version: nginx/1.23.4
```
How to upgrade Nginx to last version ?

**Comment by ononoki1** [comment]
How do you install nginx-http3? Do you run the following commands?
```
wget https://github.com/ononoki1/nginx-http3/releases/latest/download/nginx.deb
sudo apt install ./nginx.deb
```
When installing, you should see output saying that the installed version is 1.25.1.

**Comment by ononoki1** [comment]
The output during installation should be like this:
```
Get:1 /path/to/nginx.deb nginx amd64 1.25.1-1~bullseye [1883 kB]
Preparing to unpack /path/to/nginx.deb ...
----------------------------------------------------------------------

Thanks for using nginx!

Please find the official documentation for nginx here:
* https://nginx.org/en/docs/

Please subscribe to nginx-announce mailing list to get
the most important news about nginx:
* https://nginx.org/en/support.html

Commercial subscriptions for nginx are available on:
* https://nginx.com/products/

----------------------------------------------------------------------
Unpacking nginx (1.25.1-1~bullseye) ...
Setting up nginx (1.25.1-1~bullseye) ...
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service -> /lib/systemd/system/nginx.service.
```
So, obviously the version is 1.25.1.

If you run `nginx -v` and see `nginx version: nginx/1.23.4`, you can just ignore it since it's not the actual version.

**Comment by iwebroot** [comment]
> How do you install nginx-http3? Do you run the following commands?
> 
> ```
> wget https://github.com/ononoki1/nginx-http3/releases/latest/download/nginx.deb
> sudo apt install ./nginx.deb
> ```
> 
> When installing, you should see output saying that the installed version is 1.25.1.

Yes I used those command lines.

> The output during installation should be like this:
> 
> ```
> Get:1 /path/to/nginx.deb nginx amd64 1.25.1-1~bullseye [1883 kB]
> Selecting previously unselected package nginx.
> (Reading database ... 31922 files and directories currently installed.)
> Preparing to unpack /path/to/nginx.deb ...
> ----------------------------------------------------------------------
> 
> Thanks for using nginx!
> 
> Please find the official documentation for nginx here:
> * https://nginx.org/en/docs/
> 
> Please subscribe to nginx-announce mailing list to get
> the most important news about nginx:
> * https://nginx.org/en/support.html
> 
> Commercial subscriptions for nginx are available on:
> * https://nginx.com/products/
> 
> ----------------------------------------------------------------------
> Unpacking nginx (1.25.1-1~bullseye) ...
> Setting up nginx (1.25.1-1~bullseye) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service -> /lib/systemd/system/nginx.service.
> ```
> 
> So, obviously the version is 1.25.1.
> 
> If you run `nginx -v` and see `nginx version: nginx/1.23.4`, you can just ignore it since it's not the actual version.

Thank you for this clarification.
