### ISSUE TITLE
BoringSSL

### ISSUE THREAD

**Issue by iz8mbw** [ononoki1/nginx#46]
Hello.
No way to use (again) BoringSSL instead to use quictls?

**Comment by ononoki1** [comment]
quictls is better since boringssl does not support some functions (e.g. ocsp stapling). It is **possible** to use boringssl but not **reasonable**.

**Comment by iz8mbw** [comment]
Reasonable or nor I suppose is an user choices.
Exists also other libraries that supports Http3 such as quiche and LibreSSL...

Maybe can useful to have 2 versions, one using BoringSSL and one use quictls.
